# torchtitan Config.toml

[job]
dump_folder = "/home/bloc/torchtitan-dumps"
description = "DeepSeek v3 1b DeMo training hsdp"
print_args = false
use_for_integration_test = false

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 10
enable_memory_snapshot = false
save_memory_snapshot_folder = "memory_snapshot"

[metrics]
log_freq = 1
disable_color_printing = false
enable_tensorboard = false
save_tb_folder = "tb"
enable_wandb = true

[model]
name = "deepseek_v3_dense"
flavor = "test_1b"
# test tokenizer.model, for debug purpose only
tokenizer_path = "./configs/tokenizers/llama3_8b_truncated_32000.model"
# converters = ["float8"]

[optimizer]
name = "AdamW"
lr = 4e-4
#overlapped = true
#nesterov = true

[lr_scheduler]
warmup_steps = 1000  # lr scheduler warm up, normally 20% of the train steps
decay_ratio = 0.8  # lr scheduler decay ratio, 80% of the train steps
decay_type = "cosine"
lr_min = 0.1

[training]
local_batch_size = 32
global_batch_size = 1024
seq_len = 2048
max_norm = 1.0  # grad norm clipping
steps = 5000
compile = true
dataset = "c4_local"  # supported datasets: c4_test (2K), c4 (177M)
# force_default_precision = "bfloat16"
seed = 42
# mixed_precision_param = "bfloat16"
# mixed_precision_reduce = "bfloat16"

[parallelism]
data_parallel_replicate_degree = 8
data_parallel_shard_degree = 4
fsdp_reshard_after_forward = "default" # default / never / always
tensor_parallel_degree = 1
enable_async_tensor_parallel = false
pipeline_parallel_degree = 1
context_parallel_degree = 1
#force_disable_gradient_all_reduce = true

[checkpoint]
enable_checkpoint = false
folder = "/home/bloc/torchtitan-checkpoints/deepseek-1b-DeMo-hsdp-test-big-tokenizer"
interval = 1000
last_save_model_weights_only = false
# export_dtype = "float32"
export_dtype = "bfloat16"
async_mode = "disabled"  # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = "none"  # ["none", "selective", "full"]
selective_ac_option = '2'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_fsdp_float8_all_gather = false
precompute_float8_dynamic_scale_for_fsdp = false
force_recompute_fp8_weight_in_bwd = false
filter_fqns = ["output"]
